### ISSUE TITLE
addObjectWhereUsed producing a lot of warnings/errors

### ISSUE THREAD

**Issue by bethatasitmay** [PaloAltoNetworks/pan-os-php#644] opened 2022-08-31 06:57 UTC
## Describe the bug

This command is producing very unexpected output:

pan-os-php type=address in=api://panorama location=any actions=addObjectWhereUsed:new-host 'filter=(name eq current-host)'

## Expected behavior

The new-host address object should be added wherever the current-host address object appears.

## Current behavior

I get lots of about address objects or groups in address groups as well as errors about address groups being involved in loop usage:

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: VPN-Employee-Nets
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: BI-Cluster is added as subgroup to servicegroup: MSSQL-Servers
XML line #630761, XPATH: /config/shared/address-group/entry[@name='BI-Cluster']

* ** WARNING ** * addressgroup with name: App-Servers-2 is added as subgroup to servicegroup: PRD-App-Servers-1
XML line #633990, XPATH: /config/shared/address-group/entry[@name='App-Servers-2']

* ** WARNING ** * addressgroup with name: Active-Directory-Clients-2 is added as subgroup to servicegroup: Active-Directory-Clients-1
XML line #630253, XPATH: /config/shared/address-group/entry[@name='Active-Directory-Clients-2']

* ** WARNING ** * addressgroup with name: All-User-Nets-2 is added as subgroup to servicegroup: All-User-Nets-1
XML line #633131, XPATH: /config/shared/address-group/entry[@name='All-User-Nets-2']

* ** WARNING ** * addressgroup with name: Domain-Controllers-2 is added as subgroup to servicegroup: Domain-Controllers-1
XML line #629835, XPATH: /config/shared/address-group/entry[@name='Domain-Controllers-2']

* ** WARNING ** * addressgroup with name: BI-Cluster is added as subgroup to servicegroup: PRD-Windows-Servers-1
XML line #630761, XPATH: /config/shared/address-group/entry[@name='BI-Cluster']

* ** WARNING ** * addressgroup with name: All-GlobalProtect-Nets is added as subgroup to servicegroup: VPN-Employee-Nets
XML line #632401, XPATH: /config/shared/address-group/entry[@name='All-GlobalProtect-Nets']

* ** WARNING ** * addressgroup with name: App-Servers-2 is added as subgroup to servicegroup: PRD-App-Servers-1
XML line #633990, XPATH: /config/shared/address-group/entry[@name='App-Servers-2']

* ** WARNING ** * addressgroup with name: PRD-App-Servers-1 is added as subgroup to servicegroup: PRD-Servers-2
XML line #629572, XPATH: /config/shared/address-group/entry[@name='PRD-App-Servers-1']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: VPN-Employee-Nets
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: VPN-Employee-Nets is added as subgroup to servicegroup: Exchange-Clients
XML line #628748, XPATH: /config/shared/address-group/entry[@name='VPN-Employee-Nets']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: VPN-Employee-Nets
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: User-Networks-3 is added as subgroup to servicegroup: SharePoint-Clients
XML line #624931, XPATH: /config/shared/address-group/entry[@name='User-Networks-3']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: Security-Dept
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: VPN-NC-NETWORKS
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: Security-Dept
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: SSL-VPN-NC-NETWORKS
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: VPN-Employee-Nets
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: BI-Cluster is added as subgroup to servicegroup: PRD-Windows-Servers-1
XML line #630761, XPATH: /config/shared/address-group/entry[@name='BI-Cluster']

* ** WARNING ** * addressgroup with name: VPN-Employee-Nets is added as subgroup to servicegroup: Patch-Clients
XML line #628748, XPATH: /config/shared/address-group/entry[@name='VPN-Employee-Nets']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: VPN-Employee-Nets
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: Security-Dept is added as subgroup to servicegroup: WSUS-Clients
XML line #624807, XPATH: /config/shared/address-group/entry[@name='Security-Dept']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: Security-Dept
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: SSL-VPN-NC-NETWORKS
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: Security-Dept
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: VPN-NC-NETWORKS
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: Active-Directory-Clients-1 is added as subgroup to servicegroup: Active-Directory-Clients-2
XML line #626760, XPATH: /config/shared/address-group/entry[@name='Active-Directory-Clients-1']

* ** WARNING ** * addressgroup with name: All-User-Nets-2 is added as subgroup to servicegroup: All-User-Nets-1
XML line #633131, XPATH: /config/shared/address-group/entry[@name='All-User-Nets-2']

* ** WARNING ** * addressgroup with name: BI-Cluster is added as subgroup to servicegroup: PRD-Windows-Servers-1
XML line #630761, XPATH: /config/shared/address-group/entry[@name='BI-Cluster']

* ** WARNING ** * addressgroup with name: All-GlobalProtect-Nets is added as subgroup to servicegroup: VPN-Employee-Nets
XML line #632401, XPATH: /config/shared/address-group/entry[@name='All-GlobalProtect-Nets']

* ** WARNING ** * addressgroup with name: Domain-Controllers-2 is added as subgroup to servicegroup: Active-Directory-Clients-2
XML line #629835, XPATH: /config/shared/address-group/entry[@name='Domain-Controllers-2']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: VPN-Employee-Nets
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: App-Servers-2 is added as subgroup to servicegroup: PRD-DirService
XML line #633990, XPATH: /config/shared/address-group/entry[@name='App-Servers-2']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: VPN-Employee-Nets
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: All-User-Nets-1 is added as subgroup to servicegroup: CitrixDeliveryAgents
XML line #624813, XPATH: /config/shared/address-group/entry[@name='All-User-Nets-1']

* ** WARNING ** * addressgroup with name: All-GlobalProtect-Nets is added as subgroup to servicegroup: VPN-Employee-Nets
XML line #632401, XPATH: /config/shared/address-group/entry[@name='All-GlobalProtect-Nets']

* ** WARNING ** * addressgroup with name: All-GlobalProtect-Nets is added as subgroup to servicegroup: VPN-Employee-Nets
XML line #632401, XPATH: /config/shared/address-group/entry[@name='All-GlobalProtect-Nets']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: VPN-Employee-Nets
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup with name: Portal-InfoSec is added as subgroup to servicegroup: VPN-Employee-Nets
XML line #628167, XPATH: /config/shared/address-group/entry[@name='Portal-InfoSec']

* ** WARNING ** * addressgroup: IN-Exchange-Servers-dupe is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Security-Dept is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: InfoSec-Scanning-Servers is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: V-Agents is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: SIEMs is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Servers-for-Monitoring is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: ssh-clients-1 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: ssh-clients-2 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: ssh-servers-2 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: SSH-Servers-3 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: BI-Servers is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: PRD-Windows-Servers-1 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: PRD-DirService is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: PRD-App-Servers-2 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: PRD-LAP is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Scanning-Server-Clients is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: BUILDGRP-RDP-Targets is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Clients-4 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Storage-MGMT is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Portal-Destinations is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: PRD-Address-Parsers is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: VPN-User-PAT-Targets is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Cluster-IPMI-All is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Monitoring-Clients is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: PRD-PhoneVal-Servers is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Clients-5 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Web-Servers-6 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: DNS-Servers-External-Queries is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Domain-Controllers-SC is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: DNS-Servers is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: FW-Users-Nets-All-3 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: FW-Users-Nets-All-3-CIFS is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: DNS-Servers-Internal-Queries is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: SSL-VPN-NETWORKS is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: User-Nets-4 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Web-Application-Users-5 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: SSO-Remote-User-Nets is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Clients-7 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Clients-8 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: CitrixDeliveryAgents is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Clients-9 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Clients-10 is maybe not listed as it is involved in a loop usage

* ** WARNING ** * addressgroup: Clients-11 is maybe not listed as it is involved in a loop usage

* ** ERROR ** * cannot determine groups dependencies after 40 loops iterations: is there too many nested groups?

In addition, note that for the initials warnings where an XML line is listed.  All of them are listed as a line >600K.  My Panorama XML config maxes out at 329,918 lines.

## Possible solution

Unknown - it used to work fine.  I've run this command many, many times and this is the first time I received any kind of error that wasn't due to operator error (typo, missing object, etc.).

## Steps to reproduce

run this command, where new-host and current-host are existing address objects, new-host is not currently a member of any address group, and current-host is a member of 3 address groups (none of which are listed in the errors/warnings):

pan-os-php type=address in=api://panorama.domain.com location=any actions=addObjectWhereUsed:new-host 'filter=(name eq current-host)'

## Context

I need to setup firewall rules for 6 new hosts that are replacing 6 current hosts.  I only tried the first one.

## Your Environment

- Version used: 2.0.55
- Operating System and version (desktop or mobile): Windows 10

**Comment by swaschkut** [comment] 2022-08-31 07:36
this is NOT a bug, [only one part there is  a typo in the warning "service group"]
this is an improved validation of your configuration.

your addressgroups are creating a loop.

And as you where running this many times before,
one of your last configuration changes brought this up.

**Comment by swaschkut** [comment] 2022-08-31 07:46
you will get the same warning / error if you are running only with DISPLAY, also if no filter is set

pan-os-php type=address in=api://panorama location=any actions=display 'filter=(name eq current-host)'

**Comment by bethatasitmay** [comment] 2022-08-31 17:16
All of them are duplicates or just the ones that warn about loops?

Also, what about the XML line numbering?

**Comment by swaschkut** [comment] 2022-09-01 07:24
regarding line numbering,
I recommend to load your XML config file into a XML reader where you can generate a pretty XML;
then you will see the line mentioned here.

- no clue where you are seeing duplicates, please the loop detection is working this way:

address-group example:
- grpA has member grpB
- grpB has member grpC
- grpC has member grpA

**Comment by bethatasitmay** [comment] 2022-09-01 16:53
Yeah, I get the loop part of it (we've had that problem before and on Juniper firewalls).  I spot checked one group with which I'm very familiar and didn't find a loop.  It's a group we no longer need (there's an address object in it that is the only thing needed so I'm swapping out the group for that object and I'll see if that one goes away.

**Comment by bethatasitmay** [comment] 2022-09-05 22:04
I spot checked a few of the flagged groups and none of them had loops nor did they have a large number of members or nested groups.

**Comment by bethatasitmay** [comment] 2022-09-05 22:05
Deleting a flagged group dropped it out of the list of errors, as expected.

**Comment by swaschkut** [comment] 2022-09-05 23:28
version 2.0.57 - removed the additional loop check

**Comment by swaschkut** [comment] 2022-09-06 19:35
if it is not done - why you are not reopen this issue?

**Comment by swaschkut** [comment] 2022-09-06 19:43
if the actual fix is not helping you, I recommend to to share more detailed information about the behaviour and also demo config where this problem is happen.

Right now, I can not reproduce your situation

**Comment by bethatasitmay** [comment] 2022-09-06 20:09
I still get the same exact errors on 2.0.58 as I did on 2.0.55 (minus the groups I have since deleted or removed any nested groups).

I can't share it publicly.  Also, my Panorama config has over 300K lines in it.  I've been going through the groups that have the warnings/errors above (which have been sanitized but I know how I translated them) and cleaning them up where I can.  I also checked for loops, too many group members, and groups with a lot of nesting (I don't know what the limit is).  So far, the deepest nesting is 3 (a group within a group within a group), but I haven't checked all of them, yet.

**Comment by bethatasitmay** [comment] 2022-09-06 20:59
Correction: The "...is maybe not listed as it is involved in a loop usage" lines have disappeared after at least one of my group deletions.

**Comment by swaschkut** [comment] 2022-09-07 06:02
so you are still getting this error message:
"** ERROR ** * cannot determine groups dependencies after 40 loops iterations: is there too many nested groups?"

As this is specific to your configuration file, and I still can not reproduce your exact issue.

I assume you still have my mail address, please let us move there to discuss how we can proceed

**Comment by bethatasitmay** [comment] 2022-09-07 16:26
Okay, with that fixed, the "...40 loop iterations..." message went away and the command I was trying to run finished.  There were still the Warnings, however.  I'll need to dig into those to see why.

Do the Warning messages happen any time there are nested groups?

**Comment by swaschkut** [comment] 2022-09-07 19:14
in the next version; these warnings will disappear.

and if a loop is found, it will at least point you into the Device-Group where this is happen, and also display the relevant address-groups with its subgroups.

2.0.58 will be reused for this and massiv extended also with also new features and some bugfixes for other parts

**Comment by swaschkut** [comment] 2022-09-08 13:27
please validate with latest version,
version is still 2.0.58, but with extended feature

**Comment by bethatasitmay** [comment] 2022-09-08 14:23
I ran the same command, but as an action=display and all of the Warnings went away.  Thanks!

**Comment by swaschkut** [comment] 2022-09-08 15:02
then I am closing this

**Closed by swaschkut** 2022-09-08 15:02 UTC
Labels: question
