### ISSUE TITLE
Question - related to Panorama objects 'override' and 'revert' => pan-os-php merger scripts

### ISSUE THREAD

**Issue by madmann26** [PaloAltoNetworks/pan-os-php#378] opened 2022-01-06 13:32 UTC
Sven,

How does 'override' and 'revert' work in the tool when compared to Panorama?

Let's say I have objects (addresses, tags, address-groups, etc) that are overridden and I want to revert those. Is there a way to this without clicking 500 objects and clicking 'revert'?

Thanks for supporting the community.

(I did look for this in the documentation first :))

**Comment by swaschkut** [comment] 2022-01-07 08:57
thanks for answering this question.

the merger scripts mentioned below, can not only do 'revert', these tools can also find similar objects, in specific for address value.
With these script you can improve your whole Panorama DG hierarchy objects and reduce complexity.

example:
pan-os-php type=address-merger
pan-os-php type=addressgroup-merger
pan-os-php type=tag-merger
pan-os-php type=service-merger
pan-os-php type=servicegroup-merger

detail command for address objects;
pan-os-php type=address-merger help

you file something like this:
 - DupAlgorithm=SameAddress | Identical | WhereUsed
     Specifies how to detect duplicates:
  - SameAddress: objects with same Network-Value will be replaced by the one picked (default)
  - Identical: objects with same network-value and same name will be replaced by the one picked
  - WhereUsed: objects used exactly in the same location will be merged into 1 single object and all ports covered by these objects will be aggregated

this is an example of the full command for address objects
pan-os-php type=address-merger in=Panoramaconfig.xml out=Panoramamerged.xml DupAlgorithm=identical location=any allowmergingwithupperlevel


if a specific DupAlgorithm is not available, like "pa_tag-merger dupalgorithm=samename", but you like to have it,
please reach out, it is always possible to extend this

**Comment by madmann26** [comment] 2022-01-07 13:35
Thanks for the notes Sven,

When running it against a .xml file, I received the following error:

** ERROR ** * Died on user notice or warning!! Error: Trying to get property of non-object on D:\Pan_Configurator\pan-os-php-windows-package\pan-os-php\lib\object-classes\Address.php:77

**Comment by swaschkut** [comment] 2022-01-10 07:48
hi,
I am interested in more details about your setup and the command you are running.
In addition it would be good to get some insights into your config.

Please reach out to `swaschkut at PaloAltoNetworks . com`

**Comment by swaschkut** [comment] 2022-01-10 12:04
to update this issue here.
the found error above is related to a bug which was just fixed in pan-os-php;
The problem is related to DeviceGroups which have in the XML part no "address" section available,
and the framework did not automatically create this XML section.

**Closed** 2022-01-11 08:12 UTC
